@isTest
private class TestSheduleOverdue 
{
/*
    static testMethod void myUnitTest() 
    {
        // TO DO: implement unit test
        Test.startTest();
        datetime myDate = datetime.newInstance(2011, 10, 19, 12, 30, 2);
        
        Applicant__c applicant=new Applicant__c(Name__c='testname',Manager_Email__c='rangambr@gmail.com',Status__c='Scheduled',Interview_Time__c=myDate);
        
        List<Applicant__c> apps=new List<Applicant__c>();
        apps.add(applicant);
        
        insert apps;
        
        SheduleOverdueChecker shc=new SheduleOverdueChecker();
        String schedule='0 0 23 * * ?';
        System.schedule('Test Shedule',schedule, shc);
        //System.assertEquals('Over due', apps[0].status__c);
        Test.stopTest();
    }*/
}